### ISSUE TITLE
Escape Quotation marks when rendering template

### ISSUE THREAD

**Issue by nelson-lojo** [ace-lab/pl-faded-parsons#11]
See behavior of the following `question.html`

```xml
<!-- AUTO-GENERATED FILE -->
<pl-question-panel>
<pl-question-panel>
<markdown>
The MPAA rating PG-13 was introduced in 1984.  Enhance the Movie class to check that the "PG-13" rating is only accepted as valid if the movie was released on or after 1-Jan-1984.
Recall that:
* `validate :my_validation_method` calls the instance method my_validation_method on the model object to be validated
* The `release_date` attribute is a Ruby Time object; these can be compared directly using <=>, <, >, etc. You can create a Time object from a date string by saying Time.parse("1/1/1984"). You can assume the release_date is always valid.
* Calling `errors.add(:field, "message")` on the model object to be validated adds a validation error associated with the attribute named field, with the explanatory message message; for example, `errors.add(:title, "cannot be blank")`
NOT ALL BLANKS MAY NEED TO BE FILLED IN, but you shouldn't need to add any blanks.
</markdown>
</pl-question-panel>
</pl-question-panel>
<!-- see README for where the various parts of question live -->
<pl-faded-parsons>
  class Movie < ActiveRecord::Base
    ?validate :rating_consistent_with_date?
    def ?rating_consistent_with_date?()
      pg13_invented = Time.parse "1/1/1984"
      if (?pg13_invented > self.release_date?) and (?self.rating == 'PG-13'?)
         ?self?.errors.add(:rating, 'only valid for 1984 and later')
      end
    end
  end
</pl-faded-parsons>
```

![image](https://github.com/ace-lab/faded-parsons-element/assets/31297176/89089a09-cfce-4a8c-98a2-d803b46ff830)

**Comment by a544266477** [comment]
The newest version of element whose commit is 1c6dcc can't escape '>' mark. After filling in '>' in any blank of a question and submitting, it will make the blank become like the photo showed below.
![image](https://github.com/ace-lab/pl-faded-parsons/assets/107975870/e4615aa5-f372-4b5b-a511-6b59cfb91992)

**Comment by nelson-lojo** [comment]
I have determined that the cause of the problem with the `>` symbol is due to the code formatting library after we render the mustache. For some reason, it interprets the contents of the `value=""` attribute of the input tag as code, applying tags and resulting in some tag soup. 

The fix was to constrain the syntax highlighting to the segments of text around the input fields. (along with a bit of pushing it to look the same)
