### ISSUE TITLE
if grader run with empty student solution, PL throws an error rather than showing "0%"

### ISSUE THREAD

**Issue by armandofox** [ace-lab/pl-faded-parsons#14]
If the solution tray is empty and the student hits "save and grade", PL will report an error `File was missing 'contents' property` (presumably referring to the `contents` property of the humongous JSON file that contains all the stuff passed to the external grader).
The correct behavior should be that `server.py` either says that the response is ungradeable, or gives 0%.  Ungradeable is probably preferred but either would be better than having PL itself give an error.

**Comment by nelson-lojo** [comment]
I assume that the autograder used in this case is the Ruby autograder? This issue will be moved to that repo: [link](https://github.com/ace-lab/ruby-autograder/issues/2).
