### ISSUE TITLE
Rebuilding the Faded Parsons Mustache + JS Element Renderer

### ISSUE THREAD

**Issue by SybelBlue** [ace-lab/pl-faded-parsons#3]
We are trying to rebuild a system that already exists, minimizing JS where possible, and maximizing mustache + Python. We need the result to:
- [ ] Take in XML and check for well-formedness
- [ ] Allow for fpp codelines that 
    - [x] Are generated in the mustache (not JS)
    - [x] Can be reordered and indented with a mouse
    - [ ] Have general syntax highlighting (not in the blanks)
    - [ ] Can be optionally marked as part of the “given”
- [ ] Allow for inline blanks that
    - [ ] Can have starter text
    - [ ] Have a minimum width
    - [ ] Resize to fit (reasonably) long text
- [ ] Allow for fpp elements to emit on-demand:
    - [ ] Well-formed student code (with indents and ordering)
    - [ ] Data that can be used to restore student state on page reload (data can be in language/format of choice)
- [ ] Be written in the traditional PrairieLearn style

This new system does *not* need:
- The element to be aware of the solution or the prompt
- The element to understand the `fpp_generator.py` faded parsons language

**Comment by nelson-lojo** [comment]
#7

**Comment by nelson-lojo** [comment]
#7 Has some desired avenues for improvement (and so might help influence design here)

**Comment by SybelBlue** [comment]
A major refactoring took place, but another may be warranted in the future. Closing this issue as wontfix for now.
